## Задача №5: Кодирование категориального признака с использованием One-Hot Encoding

Для выполнения этой задачи мы выберем категориальный признак `Sex` из набора данных `Titanic` и применим к нему метод One-Hot Encoding.

In [1]:
import pandas as pd
import numpy as np

# Load the Titanic dataset
df = pd.read_csv('https://raw.githubusercontent.com/datasciencedojo/datasets/master/titanic.csv')

print("Original DataFrame head:")
display(df.head())

Original DataFrame head:

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

### One-Hot Encoding признака 'Sex'

Применим `pd.get_dummies` для выполнения One-Hot Encoding для признака `Sex`.

In [2]:
# Perform one-hot encoding on the 'Sex' column
df_encoded = pd.get_dummies(df, columns=['Sex'], drop_first=True)

print("DataFrame after One-Hot Encoding for 'Sex' (with 'Sex_male' column):")
display(df_encoded.head())

DataFrame after One-Hot Encoding for 'Sex' (with 'Sex_male' column):

,PassengerId,Survived,Pclass,Name,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Sex_male
0,1,0,3,"Braund, Mr. Owen Harris",22.0,1,0,A/5 21171,7.2500,NaN,S,True
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",38.0,1,0,PC 17599,71.2833,C85,C,False
2,3,1,3,"Heikkinen, Miss. Laina",26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,False
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",35.0,1,0,113803,53.1000,C123,S,False
4,5,0,3,"Allen, Mr. William Henry",35.0,0,0,373450,8.0500,NaN,S,True

## Задача №25: Обнаружение и удаление выбросов на основе межквартильного размаха (IQR)

Для выполнения этой задачи мы выберем числовой признак `Fare` из набора данных `Titanic` и проведем обнаружение и удаление выбросов на основе межквартильного размаха (IQR).

In [3]:
# For outlier detection, we will use the original dataframe or a copy if modifications were made above.
# Let's use the df_encoded for continuity, assuming we want to apply this after encoding.

# Calculate Q1, Q3, and IQR for the 'Fare' column
Q1 = df_encoded['Fare'].quantile(0.25)
Q3 = df_encoded['Fare'].quantile(0.75)
IQR = Q3 - Q1

# Define bounds for outliers
lower_bound = Q1 - 1.5 * IQR
upper_bound = Q3 + 1.5 * IQR

print(f"Q1 (Fare): {Q1}")
print(f"Q3 (Fare): {Q3}")
print(f"IQR (Fare): {IQR}")
print(f"Lower Bound (Fare): {lower_bound}")
print(f"Upper Bound (Fare): {upper_bound}")

# Identify outliers
outliers = df_encoded[(df_encoded['Fare'] < lower_bound) | (df_encoded['Fare'] > upper_bound)]

print("\nNumber of outliers detected in 'Fare' column:", len(outliers))
print("\nOutliers in 'Fare' column:")
display(outliers[['Fare']].head())

Q1 (Fare): 7.9104
Q3 (Fare): 31.0
IQR (Fare): 23.0896
Lower Bound (Fare): -26.724
Upper Bound (Fare): 65.6344

Number of outliers detected in 'Fare' column: 116

Outliers in 'Fare' column:

        Fare
1    71.2833
27  263.0000
31  146.5208
34   82.1708
52   76.7292

In [4]:
# Remove outliers from the DataFrame
df_no_outliers = df_encoded[(df_encoded['Fare'] >= lower_bound) & (df_encoded['Fare'] <= upper_bound)]

print("\nDataFrame head after removing outliers from 'Fare' column:")
display(df_no_outliers.head())
print(f"Original DataFrame shape: {df_encoded.shape}")
print(f"DataFrame shape after outlier removal: {df_no_outliers.shape}")

DataFrame head after removing outliers from 'Fare' column:

,PassengerId,Survived,Pclass,Name,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Sex_male
0,1,0,3,"Braund, Mr. Owen Harris",22.0,1,0,A/5 21171,7.2500,NaN,S,True
2,3,1,3,"Heikkinen, Miss. Laina",26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,False
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",35.0,1,0,113803,53.1000,C123,S,False
4,5,0,3,"Allen, Mr. William Henry",35.0,0,0,373450,8.0500,NaN,S,True
5,6,0,3,"Moran, Mr. James",NaN,0,0,330877,8.4583,NaN,Q,True

Original DataFrame shape: (891, 12)
DataFrame shape after outlier removal: (775, 12)